Update expo-ci.yml

diff --git a/.github/workflows/expo-ci.yml b/.github/workflows/expo-ci.yml
--- a/.github/workflows/expo-ci.yml
+++ b/.github/workflows/expo-ci.yml
@@ -30,13 +30,20 @@ jobs:
       #     eas build --platform android --non-interactive --profile development 
 
       - name: Send Slack Notification
-        if: success() || failure() # Send message regardless of build success/failure
+        if: success() || failure()  # Send message regardless of build success/failure
         run: |
           STATUS="success"
+      
+          # Check if the build outcome was a failure
           if [ "${{ steps.eas_build.outcome }}" == "failure" ]; then
             STATUS="failure"
           fi
+      
+          # Extract the branch name from GITHUB_REF (e.g., refs/heads/main -> main)
+          BRANCH_NAME=${GITHUB_REF#refs/heads/}
+      
+          # Send the Slack notification with the build status and branch name
           curl -X POST -H 'Content-type: application/json' \
-          --data '{
-            "text": "EAS Build Status for *Development*:\n*Build Result*: '"$STATUS"' \nPlease check the details at https://expo.dev/accounts/${{ secrets.EXPO_ACCOUNT_NAME }}/projects/${{ secrets.EXPO_PROJECT_NAME }}/builds"
-          }' ${{ secrets.SLACK_WEBHOOK }}
+            --data '{
+              "text": "*Build Result*: '"$STATUS"' \n*Branch*: '"$BRANCH_NAME"' \nPlease check the details at https://expo.dev/accounts/${{ secrets.EXPO_ACCOUNT_NAME }}/projects/${{ secrets.EXPO_PROJECT_NAME }}/builds"
+            }' ${{ secrets.SLACK_WEBHOOK }}
